### ISSUE TITLE
Array extending does not work in jQuery 3.0.0

### ISSUE THREAD

**Issue by Jivings** [mistic100/jQuery.extendext#1]
Due to this line;

```
arrayMode = $([target.toLowerCase(), 'default']).filter(['default','concat','replace','extend'])[0];
```

(https://github.com/mistic100/jQuery.extendext/blob/master/jQuery.extendext.js#L40)

In jQuery < 3.0.0 this returns at least `"default"`, in jQuery > 3.0.0 it always returns `undefined`.

**Comment by mistic100** [comment]
0.1.2 released

**Comment by Jivings** [comment]
Nice one thanks 👍
